const QuizActionType = {
    FETCH_QUIZ_QUESTIONS: 'FETCH_QUIZ_QUESTIONS',
    QUIZ_QUESTION: 'QUIZ_QUESTION',
    CURRENT_QUESTIONS: 'CURRENT_QUESTIONS',
    ANSWERS_QUESTION: 'ANSWERS_QUESTION'
}


export default QuizActionType